[package]
name = "bang"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.7.6"
clap = {version = "3.1.0", optional=true}
rustyline = {version = "9.0.0", optional=true}

[features]
default=["clap", "rustyline"]
debug = []

[lib]
required-features=[]
