[package]
name = "bang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
clap = "2.34.0"
num-traits = "0.2"
num-derive = "0.2"
rustyline = "9.0.0"

[features]
debug = []
