[package]
name = "bang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
rustyline = "9.0.0"

[dev-dependencies]
regex = "1.5.4"

[features]
debug = []
