[package]
name = "bang"
version = "0.1.0"
edition = "2021"

[dependencies]
bang-interpreter = { path = "../interpreter" }
bang-std = { path = "../std" }
bang-syntax = { path = "../syntax" }
bang-tools = { path = "../tools" }
clap = "4"
rustyline = "10"
