[package]
name = "bang-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.7.6"
bang-syntax = { path = "../syntax" }
smallvec = { version="1", features=["union"] }
smartstring = "1"

[dev-dependencies]
bang-std = { path = "../std" }

[features]
debug = []
