name: CI

on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
          override: true

      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --all
      - name: Lint
        run: cargo clippy --all -- -D warnings
      - name: Test
        run: cargo test --all --verbose

  miri:
    name: Miri (Pointer Tagging Tests)
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: -Zmiri-strict-provenance

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup

      - name: 64 bit
        run: cargo miri test value::test --target x86_64-unknown-linux-gnu
      - name: 64 bit (Big Endian)
        run: cargo miri test value::test --target mips64-unknown-linux-gnuabi64
      - name: 32 bit
        run: cargo miri test value::test --target i686-unknown-linux-gnu
