name: CI

on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
          override: true

      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --all
      - name: Lint
        run: cargo clippy --all -- -D warnings
      - name: Test
        run: cargo test --all --verbose
